version: 1.1.{build}
image: Visual Studio 2022
install:
- cmd: |
    cd "C:\Tools\vcpkg"
    git pull > NUL
    .\bootstrap-vcpkg.bat > NUL
    cd %appveyor_build_folder%
skip_commits:
  files:
    - '**/*.md'
before_build:
- cmd: vcpkg integrate install
- cmd: vcpkg upgrade --no-dry-run
- cmd: vcpkg install spdlog:x86-windows-static spdlog:x64-windows-static detours:x86-windows-static detours:x64-windows-static
- ps: Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\%APPVEYOR_PROJECT_NAME%.rc" --resource.file-version --resource.product-version
configuration: Release
platform:
- x86
- x64
build:
  project: socksifier.sln
artifacts:
- path: 'bin**\*.dll'
cache:
- c:\tools\vcpkg\installed\
deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: 'Socksifier DLL'
  provider: GitHub
  auth_token:
    secure: GvOeZH3msooHWqoQj46UsLaojyMsnudmNdfEMUSJJfrIBuLwAYaMeI5FcxKSFVv7
  artifact: /.*\.DLL/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true